name: swast_forecast
channels:
  - defaults
dependencies:
  - jupyterlab=2.1.5
  - matplotlib=3.2.2
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.7.7
  - scipy=1.5.0
  - seaborn=0.10.1
  - statsmodels=0.11.1
  - pip:
    - pmdarima==1.6.1
    - sklearn==0.0
    - fbprophet==0.6
